# Generated by Django 4.2 on 2023-05-17 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_listing', to='auctions.category'),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
